home/urls.py
app_name="home"
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.home_render,name="home_render")
]

inventor/urls.py
app_name="inventor"
from django.urls import path
from . import views

urlpatterns = [
    path('',views.invtory_render,name="invtory_render"),
     path('/add', views.add, name='add'),
      path('/quntity', views.quntity, name='quntity'),
      path('/pay_data', views.pay_data, name='pay_data'),
    path('/previous_request_list', views.previous_request_list, name='previous_request_list'),
     path('/previous_request_list/<int:id>', views.previous_request, name='previous_request'),
    path('/year', views.year_item, name='year_item'),
    path('/month', views.month_item, name='month_item'),
path('/day', views.day_item, name='day_item'),  
]

managment/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('accounts/', include('accounts.urls',namespace='accounts_detials')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('inventor',include('inventor.urls',namespace='inventor')),
]

inventor/models.py
from django.db import models
from django.utils import timezone
class items(models.Model):
    name=models.CharField(max_length=500,verbose_name="اسم المنتج")
    quntity=models.IntegerField(verbose_name="الكميه ")
    exporter=models.CharField(max_length=1000,verbose_name="المورد ")
    data=models.DateField(auto_now_add=True)
    time=models.TimeField(auto_now_add=True)
    class Meta:
        verbose_name = 'المنتجات'
        verbose_name_plural = 'المنتجات'
    def __str__(self) -> str:
        return self.name
class paydata(models.Model):
    payer_name=models.CharField(max_length=5000,verbose_name="اسم المستلم")
    quntity=models.IntegerField(verbose_name="الكميه")
    items=models.ForeignKey(items,on_delete=models.PROTECT,verbose_name="المنتج")
    exporter=models.CharField(max_length=5000,verbose_name="اسم المسلم")
    data=models.DateField(auto_now_add=True)
    time=models.TimeField(auto_now_add=True)
    class Meta:
        verbose_name = 'الاذونات'
        verbose_name_plural = 'الاذونات'
    def __str__(self) -> str:
        return self.items
class invntor(models.Model):
    items=models.ForeignKey(items,on_delete=models.PROTECT,verbose_name="المنتج")
    quntity=models.IntegerField(verbose_name="الكميه المنصرفه")
    importer=models.CharField(max_length=500,verbose_name="المنصرف له")
    data=models.DateField(auto_now_add=True)
    time=models.TimeField(auto_now_add=True)
    class Meta:
        verbose_name = 'المخزن'
        verbose_name_plural = 'المخزن'
    def __str__(self) -> str:
        return self.importer
    def save(self, *args, **kwargs):
        if self.items.quntity> 0:
            self.items.quntity -= self.quntity
            self.items.save()
            super().save(*args, **kwargs)
        
       

inventor/views.py
from django.shortcuts import render
from datetime import datetime, timedelta
from django.shortcuts import redirect, render
from django.urls import reverse
from .models import invntor,items,paydata
from .form import Addquntity,pay_request
from django.core.paginator import Paginator

def invtory_render(request):
    
    data=invntor.objects.order_by('-data','-time')
    paginator = Paginator(data, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context={"data":page_obj}
    return render(request,'inventor.html',context)
def add(request):
    if request.method=='POST':
        Addquntity_form=Addquntity(request.POST)
        if Addquntity_form.is_valid():
            myform=Addquntity_form.save(commit=False)
            myform.user=request.user
            myform.save()
            return redirect('inventor:invtory_render')
    else:
        Addquntity_form=Addquntity()    
    return render(request,'add.html',{'Addquntity_form':Addquntity_form})
def pay_data(request):
    pay_request_form=pay_request()
    if request.method=='POST':
        pay_request_form=pay_request(request.POST)
        if pay_request_form.is_valid():
            myform=pay_request_form.save(commit=False)
            myform.user=request.user
            myform.save()
            return redirect('inventor:previous_request_list')
   
    return render(request,'pay.html',{'pay_request_form':pay_request_form})
def previous_request_list(request):
    paydatalist=paydata.objects.order_by('-data','-time')
    paginator = Paginator(paydatalist, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request,'previous_request_list.html',{'paydatalist':page_obj})

def previous_request(request,id):
    previous_request=paydata.objects.get(id=id)
    return render(request,'previous_request.html',{'previous_request':previous_request})

def quntity(request):

    totalquntity=items.objects.all()
    paginator = Paginator(totalquntity, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request,'quntity.html',{'quntity':page_obj})

def year_item(request):
    last_day = datetime.today() - timedelta(days=365)
    data = invntor.objects.filter(data__gte=last_day)
    paginator = Paginator(data, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request,'year.html',{'data':page_obj})
def month_item(request):
    last_day = datetime.today() - timedelta(days=30)
    data = invntor.objects.filter(data__gte=last_day)
    paginator = Paginator(data, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request,'month.html',{'data':page_obj})

def day_item(request):
    last_day = datetime.today() - timedelta(days=1)
    data = invntor.objects.filter(data__gte=last_day)
    paginator = Paginator(data, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'day.html', {'data': page_obj})

inventor/templates/add.html
{% extends 'base.html' %}
{% block title %} اضافه منتج{% endblock %}

{%block content%}
<div class="container-fluid w-100 p-5 text-center ">
    <div class="row">
        <div class="col-12 ">

            {{quntity}}
   
                    <h3>اضافه منتج</h3>
                        {% load bootstrap4 %}                
                        <form class="w-100 p-2" method="post" enctype="multipart/form-data">
                         {% csrf_token %}
                        
                        {% bootstrap_form Addquntity_form %}
                         {% buttons %}
                        <button type="submit" class="btn btn-success w-30  text-center m-3 p-3">اضافه</button>
                        {% endbuttons %}
                      </form>
                    </div>
                </div>
                </div>
{%endblock%}

inventor/templates/day.html
{%extends 'base.html'%}
<title>{% block title %}يوم{% endblock %}</title>

{% block  content %}

<div class="container p-5">
    <h3 class="text-center p-2">بيانات اخر يوم</h3>
<table class="table table-striped table-dark text-center">
    <thead>
      <tr>
        <th scope="col">اسم المنتج</th>
        <th scope="col">الكميه المصروفه</th>
        <th scope="col"> المنصرف له</th>
        <th scope="col">تاريخ الصرف</th>
        <th scope="col">وقت الصرف</th>
      </tr>
    </thead>
    <tbody>
        {% for item in data %}
      <tr>
    <td>{{ item.items }}</td>
    <td>{{ item.quntity }}</td>
    <td>{{ item.importer }}</td>
    <td>{{ item.data }}</td>
    <td>{{ item.time }}</td>
{% endfor %}
      </tr>


    </tbody>
</table>
{% if data.has_other_pages %}          
<div class="col-lg-12  p-2 ">
  <nav aria-label="Page navigation example text-center">
     <ul class="pagination">
            
            {% if data.has_previous %}             
                <li class="page-item"><a class="page-link" href="?page={{ data.previous_page_number }}"> <</a></li>
            {% endif %}
            
            {% for i in data.paginator.page_range  %}
                      <li class="page-item"><a class="page-link" href="?page={{i}}"><span>{{i}}</span></a></li>
            {% endfor %}
            {% if data.has_next%}
                <li class="page-item"><a class="page-link" href="?page={{ data.next_page_number }}"> > </a></li>
            {% endif %}
        </ul>
      </nav>
      </div>
</div>
</div>
{% endif %}
</div>
{% endblock%}
 

inventor/templates/inventor.html
{%extends 'base.html'%}
{% block title %} المخزن{% endblock %}

{%block content%}
<div class="container p-5">
    <h3 class="text-center">منتجات مستخدمه</h3>
    <div class="container">
      <div class="row">
        <div class="col-lg-12 m-5">
          <h3 class="text-muted">عرض المنتجات المستخدمه حسب المده</h3>
          <a class="h4 m-2 text-decoration-underline text-dark"  href="{%url 'inventor:day_item'%}">يوم</a>
          <a class="h4 m-2 text-decoration-underline text-dark" href="{%url 'inventor:month_item'%}">شهر</a>
          <a class="h4 m-2 text-decoration-underline text-dark" href="{%url 'inventor:year_item'%}">سنه</a>
    
    
        </div>
      </div>
    </div>
    <div class="table-responsive">
        <table class="table table-striped table-dark text-center">
            <thead>
              <tr>
                <th scope="col">اسم المنتج</th>
                <th scope="col">الكميه المصروفه</th>
                <th scope="col"> المنصرف له</th>
                <th scope="col">تاريخ الصرف</th>
                <th scope="col">وقت الصرف</th>
              </tr>
            </thead>
            <tbody>
              {%for i in data%}
              <tr>
                <th scope="col">{{i.items.name}}</th>
                <th scope="col"> {{i.quntity}}</th>
                <th scope="col">{{i.importer}}</th>
                <th scope="col">{{i.data}} </th>
                <th scope="col">{{i.time}} </th>
              </tr>
              {%endfor%}

            </tbody>
      </table>
      <a class="text-dark text-decoration-underline h4 m-5 " href="{% url 'inventor:add' %}">اضافه منتج</a>
      {% if data.has_other_pages %}          
          <div class="col-lg-12  p-2  ">
            <nav aria-label="Page navigation example text-center">
               <ul class="pagination " >
                      
                      {% if data.has_previous %}             
                          <li class="page-item "><a class="page-link" href="?page={{ data.previous_page_number }}"> <</a></li>
                      {% endif %}
                      
                      {% for i in data.paginator.page_range  %}
                                <li class="page-item"><a class="page-link" href="?page={{i}}"><span>{{i}}</span></a></li>
                      {% endfor %}
                      {% if data.has_next%}
                          <li class="page-item"><a class="page-link" href="?page={{ data.next_page_number }}"> > </a></li>
                      {% endif %}
                  </ul>
                </nav>
                </div>
          </div>
      </div>
      {% endif %}
    </div>     
</div>



{%endblock content%}

inventor/templates/month.html
{%extends 'base.html'%}
<title>{% block title %}شهر{% endblock %}</title>

{% block  content %}

<div class="container p-5">
    <h3 class="text-center p-2">بيانات اخر شهر</h3>
<table class="table table-striped table-dark text-center">
    <thead>
      <tr>
        <th scope="col">اسم المنتج</th>
        <th scope="col">الكميه المصروفه</th>
        <th scope="col"> المنصرف له</th>
        <th scope="col">تاريخ الصرف</th>
        <th scope="col">وقت الصرف</th>
      </tr>
    </thead>
    <tbody>
        {% for item in data %}
      <tr>
    <td>{{ item.items }}</td>
    <td>{{ item.quntity }}</td>
    <td>{{ item.importer }}</td>
    <td>{{ item.data }}</td>
    <td>{{ item.time }}</td>
{% endfor %}
      </tr>


    </tbody>
</table>
{% if data.has_other_pages %}          
<div class="col-lg-12  p-2 ">
  <nav aria-label="Page navigation example text-center">
     <ul class="pagination">
            
            {% if data.has_previous %}             
                <li class="page-item"><a class="page-link" href="?page={{ data.previous_page_number }}"> <</a></li>
            {% endif %}
            
            {% for i in data.paginator.page_range  %}
                      <li class="page-item"><a class="page-link" href="?page={{i}}"><span>{{i}}</span></a></li>
            {% endfor %}
            {% if data.has_next%}
                <li class="page-item"><a class="page-link" href="?page={{ data.next_page_number }}"> > </a></li>
            {% endif %}
        </ul>
      </nav>
      </div>
</div>
</div>
{% endif %}
</div>
{% endblock%}
 

inventor/templates/pay.html
{% extends 'base.html' %}
{% block title %}  اذن الصرف{% endblock %}

{%block content%}
<div class="container-fluid w-100 p-5 text-center ">
    <div class="row">
        <div class="col-12 ">

            <h4><a class="text-decoration-underline" href="{%url 'inventor:previous_request_list'%}">عرض الاذونات السابقه</a></h4>
   
<h3>عمل اذن </h3>
                        {% load bootstrap4 %}                
                        <form class="w-100 p-2" method="post" enctype="multipart/form-data">
                         {% csrf_token %}
                        
                        {% bootstrap_form pay_request_form %}
                         {% buttons %}
                        <button type="submit" class="btn btn-success w-30  text-center m-3 p-3">عمل اذن</button>
                        {% endbuttons %}
                      </form>
                    </div>
                </div>
                </div>
{%endblock%}

inventor/templates/previous_request.html
{% extends 'base.html' %}
<title>{% block title %}الاذونات السابقه{% endblock %}</title>

{%block content%}
<div class="container-fluid">
<div class="row">
    <div class="col-lg-12">
        <h1 class="text-center p-2">اذن الصرف</h1>

        <h3 class="text-muted p-3">اسم المستلم :<span class="text-dark">{{previous_request.payer_name}}</span></h3>
        <h3 class="text-muted p-3"> الكميه :<span class="text-dark">{{previous_request.quntity}}</span></h3>
        <h3 class="text-muted p-3"> العنصر :<span class="text-dark">{{previous_request.items}}</span></h3>
        <h3 class="text-muted p-3">اسم المسلم :<span class="text-dark">{{previous_request.exporter}}</span></h3>
        <h3 class="text-muted p-3"> تاريخ التسليم :<span class="text-dark">{{previous_request.data}}</span></h3>
        <h3 class="text-muted p-3">وقت التسليم :<span class="text-dark">{{previous_request.time}}</span></h3>
        <h3 class="text-muted p-3">امضاء :</h3>
    </div>

</div>
<button class="text-center btn btn-success p-3 m-2 printbtn" onclick="window.print()">اطبع الصفحه</button>

</div>
{%endblock%}

inventor/templates/previous_request_list.html
{% extends 'base.html' %}
<title>{% block title %}الاذونات السابقه{% endblock %}</title>

{%block content%}
<div class="container-fluid w-100 p-5 text-center">
  <h2>الاذونات السابقه</h2>
    <table class="table table-striped table-dark text-center">
        <thead>
          <tr>
            <th scope="col">اسم المستلم</th>
            <th scope="col">الكميه </th>
            <th scope="col">العنصر</th>
            <th scope="col">اسم المسلم</th>
		    <th scope="col">تاريخ التسليم  </th>
		  <th scope="col">وقت التسليم</th>


          </tr>
        </thead>
        <tbody>
          {%for i in paydatalist%}
          <tr>
            <th scope="col">{{i.payer_name}}</th>
            <th scope="col"> {{i.quntity}}</th>
            <th scope="col">{{i.items}}</th>
            <th scope="col">{{i.exporter}}</th>
            <th scope="col">{{i.data}} </th>
            <th scope="col">{{i.time}} </th>
            <th scope="col "> <a class="text-light text-decoration-underline" href="{%url 'inventor:previous_request' i.id%}">عرض</a></th>

          </tr>
          {%endfor%}

        </tbody>
  </table>
  {% if paydatalist.has_other_pages %}          
  <div class="col-lg-12  p-2 ">
    <nav aria-label="Page navigation example text-center">
       <ul class="pagination">
              
              {% if paydatalist.has_previous %}             
                  <li class="page-item"><a class="page-link" href="?page={{ paydatalist.previous_page_number }}"> <</a></li>
              {% endif %}
              
              {% for i in paydatalist.paginator.page_range  %}
                        <li class="page-item"><a class="page-link" href="?page={{i}}"><span>{{i}}</span></a></li>
              {% endfor %}
              {% if paydatalist.has_next%}
                  <li class="page-item"><a class="page-link" href="?page={{ paydatalist.next_page_number }}"> > </a></li>
              {% endif %}
          </ul>
        </nav>
        </div>
  </div>
</div>
{% endif %}
  <button class="text-center btn btn-success printbtn" onclick="window.print()">اطبع الصفحه</button>

  </div>

</div>
</div>
{%endblock%}

inventor/templates/quntity.html
{% extends 'base.html' %}
<title>{% block title %}المنتجات{% endblock %}</title>

{%block content%}
<div class="container-fluid w-100 p-5 text-center">
    <table class="table table-striped table-dark text-center">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">اسم المنتج</th>
            <th scope="col">الكميه </th>
            <th scope="col">المورد</th>


          </tr>
        </thead>
        <tbody>
      
          <tr>
     
            
          </tr>
       

        </tbody>
  </table>
  <button class="text-center btn btn-success" onclick="window.print()">اطبع الصفحه</button>

  </div>

</div>
</div>
{%endblock%}

inventor/templates/year.html
{%extends 'base.html'%}
<title>{% block title %}سنه{% endblock %}</title>

{% block  content %}

<div class="container p-5">
    <h3 class="text-center p-2">بيانات اخر سنه</h3>
<table class="table table-striped table-dark text-center">
    <thead>
      <tr>
        <th scope="col">اسم المنتج</th>
        <th scope="col">الكميه المصروفه</th>
        <th scope="col"> المنصرف له</th>
        <th scope="col">تاريخ الصرف</th>
        <th scope="col">وقت الصرف</th>
      </tr>
    </thead>
    <tbody>
        {% for item in data %}
      <tr>
    <td>{{ item.items }}</td>
    <td>{{ item.quntity }}</td>
    <td>{{ item.importer }}</td>
    <td>{{ item.data }}</td>
    <td>{{ item.time }}</td>
{% endfor %}
      </tr>


    </tbody>
</table>
{% if data.has_other_pages %}          
<div class="col-lg-12  p-2 ">
  <nav aria-label="Page navigation example text-center">
     <ul class="pagination">
            
            {% if data.has_previous %}             
                <li class="page-item"><a class="page-link" href="?page={{ data.previous_page_number }}"> <</a></li>
            {% endif %}
            
            {% for i in data.paginator.page_range  %}
                      <li class="page-item"><a class="page-link" href="?page={{i}}"><span>{{i}}</span></a></li>
            {% endfor %}
            {% if data.has_next%}
                <li class="page-item"><a class="page-link" href="?page={{ data.next_page_number }}"> > </a></li>
            {% endif %}
        </ul>
      </nav>
      </div>
</div>
</div>
{% endif %}
</div>
{% endblock%}
 