home/urls.py
app_name="home"
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.home_render,name="home_render")
]

inventor/urls.py
app_name="inventor"
from django.urls import path
from . import views

urlpatterns = [
    path('',views.invtory_render,name="invtory_render"),
     path('/add', views.add, name='add'),
      path('/quntity', views.quntity, name='quntity'),
      path('/pay_data', views.pay_data, name='pay_data'),
    path('/previous_request_list', views.previous_request_list, name='previous_request_list'),
     path('/previous_request_list/<int:id>', views.previous_request, name='previous_request'),
    path('/year', views.year_item, name='year_item'),
    path('/month', views.month_item, name='month_item'),
path('/day', views.day_item, name='day_item'),  
]

managment/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('accounts/', include('accounts.urls',namespace='accounts_detials')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('inventor',include('inventor.urls',namespace='inventor')),
]

templates/base.html
{%load static%} 

<!DOCTYPE html>
<html lang="ar" dir="rtl">
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}{% endblock %}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <!-- Google Web Fonts -->
    <link href="{%static 'css/css2.css' %}" rel="stylesheet" />
    <!-- Libraries Stylesheet -->
    <link
      href="{%static 'lib/owlcarousel/assets/owl.carousel.min.css' %}"
      rel="stylesheet"
    />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{%static 'css/bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Template Stylesheet -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{%static  'css/lastt.css' %}"
      rel="stylesheet"
    />
  </head>
  <body>
    <div class="container-fluid px-5 d-none d-lg-block">
      <div class="row gx-5 py-3 align-items-center">
        <div class="col-lg-12">
          <div class="d-flex align-items-center justify-content-center">
            <a href="" class="navbar-brand ms-lg-5">
              <h1 class="m-0 display-4 title">
                <span class="fci">كليه حاسبات ومعلومات جامعه الزقازيق
              </h1>
     
            </a>
          </div>
        </div>
      </div>
    </div>
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark p-3">
      <a
        href=""
        class="navbar-brand d-flex d-lg-none"
      >
        <h1 class="m-0 display-4 text-white">كليه حاسبات ومعلومات  جامعه الزقازيق</h1>
      </a>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarCollapse"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav mx-auto py-0">
          <a
            href="{%url 'home:home_render'%}"
            class="nav-item nav-link text-light text-uppercase "
            >الصفحه الرئيسية</a
          >
          <a
          href="{%url 'inventor:quntity'%}"
          class="nav-item nav-link text-light text-uppercase "
          > جميع المنتجات</a
        >
     
   
      <a
      href="{%url 'inventor:pay_data'%}"
      class="nav-item nav-link text-light text-uppercase "
      > اذن الصرف </a>
      <a
      href="{%url 'inventor:invtory_render' %}"
      class="nav-item nav-link text-light text-uppercase "
      >ادراه المخزن</a
    >
      {%if user.is_superuser%}
      <a
      href="{% url 'admin:index' %}"
      class="nav-item nav-link text-light text-uppercase ">   الادمن</a>
      {%endif%}
      {%if user.is_authenticated %}
      <a
      href="{%url 'logout'%}"
      class="nav-item nav-link text-light text-uppercase "
      >  تسجيل خروج</a
    >
      {%else%}
      <a
      href="{%url 'login'%}"
      class="nav-item nav-link text-light text-uppercase "
      >  تسجيل دخول</a
    >
    {%endif%}


    </div>
  </div>
      </div>
    </nav>
    {% block content %} {%endblock content%}
    <div class="container-fluid  bg-dark text-white h-100 p-2">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <div class="row">
              <div class="col-lg-12 col-md-12 pt-5 mb-5">
                <h4 class="text-white text-center">جامعه الزقازيق</h4>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  

    <!-- JavaScript Libraries -->
    <script src="{%static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{%static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{%static 'lib/easing/easing.min.js' %}"></script>
    <script src="{%static  'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{%static  'lib/counterup/counterup.min.js' %}"></script>
    <script src="{%static  'lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{%static  'js/min.js' %}"></script>
  </body>
</html>

templates/base_generic.html
{%load static%} 

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}{% endblock %}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <link href="{%static 'css/css2.css' %}" rel="stylesheet" />

    <!-- Icon Font Stylesheet -->
    <link href="{%static 'css/all.min.css' %}" rel="stylesheet" />
    <link href="{%static 'css/bootstrap-icons.css' %}" rel="stylesheet" />

    <!-- Libraries Stylesheet -->
    <link
      href="{%static 'lib/owlcarousel/assets/owl.carousel.min.css' %}"
      rel="stylesheet"
    />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{%static 'css/bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Template Stylesheet -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{%static  'css/final.css' %}"
      rel="stylesheet"
    />
  </head>
    <div class="container-fluid px-5 d-lg-block">
      <div class="row gx-5 py-3 align-items-center">
        <div class="col-lg-12">
          <div class="d-flex align-items-center justify-content-center">
            <a href="{%url 'home:home_render'%}" class="navbar-brand ms-lg-5">
              <h1 class="m-0 display-4 text-success">
                <span class="text-dark"> كليه حاسبات ومعلومات جامعه الزقازيق
              </h1>
            </a>
          </div>
        </div>
      </div>
    </div>
    {% block body %} {% endblock body %}
    <!-- JavaScript Libraries -->
    <script src="{%static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{%static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{%static 'lib/easing/easing.min.js' %}"></script>
    <script src="{%static  'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{%static  'lib/counterup/counterup.min.js' %}"></script>
    <script src="{%static  'lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{%static  'js/all.js' %}"></script>

</html>